# Generated by Django 5.2 on 2026-07-31 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('organizations', '0002_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_audienc_e09e87_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='audience',
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['organization'], name='announcemen_organiz_c8fe0c_idx'),
        ),
    ]
