# Generated by Django 5.2 on 2026-08-02 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_published_at'),
        ('organizations', '0002_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='audience',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('SOCIAL', 'Social'), ('SPORTS', 'Sports'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization'], name='events_even_organiz_6d342c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
    ]
