# Generated by Django 5.2 on 2026-08-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_audience_event_organization_and_more'),
        ('organizations', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization'),
        ),
    ]
