# Generated by Django 5.2 on 2026-07-31 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('organization_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('SRC', 'SRC'), ('FACULTY', 'Faculty'), ('DEPARTMENT', 'Department'), ('SOCIETY', 'Society'), ('TEAM', 'Team'), ('CLUB', 'Club'), ('COMMITTEE', 'Committee'), ('ASSOCIATION', 'Association'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('advisor_name', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization')),
                ('registered_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_organizations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
