# Generated by Django 5.2 on 2026-07-30 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('RELIGIOUS', 'Religious'), ('TECHNOLOGY', 'Technology'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('advisor_name', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
            },
        ),
    ]
