# Generated by Django 5.2 on 2026-08-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('EVENT', 'Event'), ('ORGANIZATION', 'Organization'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], default='SYSTEM', max_length=20),
        ),
    ]
